#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: wf-proxy
  name: wf-proxy
  namespace: #@ data.values.namespace
spec:
  ports:
    - name: "2878"
      port: 2878
      targetPort: 2878
  selector:
    app: wf-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wf-proxy
  name: wf-proxy
  namespace: #@ data.values.namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wf-proxy
  strategy: {}
  template:
    metadata:
      labels:
        app: wf-proxy
    spec:
      containers:
        - env:
            - name: JAVA_HEAP_USAGE
              value: 1650m
            - name: WAVEFRONT_TOKEN
              value: #@ data.values.wavefront.token
            - name: WAVEFRONT_URL
              value: #@ "https://" + data.values.wavefront.url + "/api"
          image: harbor.dorn.gorke.ml/banking-demo/wf-proxy:latest
          name: wf-proxy
          ports:
            - containerPort: 2878
          resources: {}
      restartPolicy: Always
